apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: pcjoshidotnetconf 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pcjoshidotnetconf 
    spec:
      containers:
        - name: pcjoshidotnetconf 
          image: rlincregistry.azurecr.io/pcjoshidotnetconf
          ports:
          - containerPort: 80